### ISSUE TITLE
Great program/ Small Issues

### ISSUE THREAD

**Issue by forsomefun** [dchang0/torrentwatch-xa#2] opened 2018-04-27 13:22 UTC
This program is great and is the easiest for a novice like me to get set up. I tried a few other programs but now of them would configure correctly. I am going to combine a few things together. 

- Matching has files in it, that do not appear in downloaded but have been added to transmission and completed. 

- I do think that knowing what file it will download is a little confusing. I assuming it is just the favorites, but I am not 100 percent sure.

- How often does it update the feed? I don't see any options to change that from the menu

- A small error is that I changed my directory it keeps saying the folder does not exist, but it does work

**Comment by dchang0** [comment] 2018-04-27 15:46
Hi--

Thanks for trying out torrentwatch-xa and letting me know about these issues.

I'll answer them in separate posts. First:

Re: "Matching has files in it, that do not appear in downloaded but have been added to transmission and completed."

Could you provide a screenshot or describe what you did in more detail? I'm not sure what you're seeing.

I can say for sure that in theory, the Matching filter can show items that do not appear in the Downloaded filter, but I'll need to know more in order to explain exactly why you're seeing what you're seeing.

**Comment by dchang0** [comment] 2018-04-27 15:50
Re: "I do think that knowing what file it will download is a little confusing. I assuming it is just the favorites, but I am not 100 percent sure."

You are correct. torrentwatch-xa will only auto-download Favorites that it finds in the feeds. If it finds more than one item that matches a given Favorite, it will auto-download the first one it encounters (so the order of feeds matters, and the timestamp of the item in its feed matters) and then ignore the others that match.

For example, if you have one Favorite that shows up in Feed A, B, and C, there will be three items highlighted in the All and Matching filters. Let's say Feed B was the first to post the item; torrentwatch-xa will download Feed B's item, and Feed A and C's items will show as matches but will not download.

**Comment by dchang0** [comment] 2018-04-27 16:14
Re: "How often does it update the feed? I don't see any options to change that from the menu"

This can't be controlled from within torrentwatch-xa because it's set by the cron job.

Edit this file:

/etc/cron.d/torrentwatch-xa-cron

This is the line that you'll want to change.

`*/15 * * * * www-data /usr/bin/php -q /var/lib/torrentwatch-xa/twxacli.php >/dev/null 2>&1`

The */15 means that it will check every 15 minutes.

I do not recommend checking more often than every 15 minutes; the benefit to doing so is pretty small. The lowest I'd go is once every 10 minutes.

If you reduce the cron job interval to 5 minutes or lower, you'll have to find the cache age checks in the source code and reduce those to something shorter so that the feed caches expire faster.

**Comment by dchang0** [comment] 2018-04-27 16:15
Re: "A small error is that I changed my directory it keeps saying the folder does not exist, but it does work"

Another person reported the exact same problem. I'm working on this and will almost certainly have it fixed in the next release, maybe sooner.

**Comment by forsomefun** [comment] 2018-04-27 17:05
![screenshot_chrome_beta_20180427-115846](https://user-images.githubusercontent.com/25670034/39375227-34aa17e0-4a13-11e8-9cd2-94a16d5fa6c4.png)

**Comment by dchang0** [comment] 2018-04-27 17:30
Thanks for the screenshots--they are a huge help!

The dark blue items in the Matching list that are not in the Downloaded list are normal. Those are "Old Favorite" items, which mean the episode number is older than the episode number of the newest matching item in the download cache.

For instance, "The Americans" is at 6x5 (Season 6, Episode 5). The favorite for "The Americans" probably says 6x6 (Season 6, Episode 6), so it is ignoring 6x5 and 6x4 (you can see 6x4 further down the screen, near the bottom).

The two red items at the top with an error message have to do with Transmission not being able to find or access what it was downloading. It's best to clear any broken downloads in Transmission itself, then restart them.

You definitely need to fix the download_dir problem first, though. Transmission cannot download to the path /root/Downloads because it either doesn't exist or does not have the correct permissions for Transmission to write to it.

**Comment by forsomefun** [comment] 2018-04-27 18:29
If it is not to complicated could you explain how to five transmission the permission.

Originally I thought this was a big because. I can go to /root/Downloads and see that the files have been downloading to /root/Downloads from torrenrwatch via transmission

**Comment by dchang0** [comment] 2018-04-27 19:31
It's pretty easy to do if you do it the super-insecure way.

First, check the permissions with:

`ls -ld /root/Downloads`

Then, change the permissions to wide-open with:

`chmod 777 /root/Downloads`

But this is VERY insecure. I would only do this for testing to see if the error message goes away. If it does, then yes, permissions were the problem. You might have to restart the Transmission daemon (or just reboot the server--it will be faster).

To change the permissions back, issue:

`chmod 700 /root/Downloads`

700 might be incorrect; it is the same as rwx------, which you should have seen in step 1 like this:

`drwx------`

If this does fix the error, then what I recommend is that you choose some other directory to store your downloaded torrents in, something that doesn't belong to root so that the security can be set lower and not put your OS at risk of hacking.

Anything under `/root` with wide-open permissions is going to be dangerous.

**Comment by dchang0** [comment] 2018-05-10 01:47
Hi, forsomefun-- Just checking to see if this issue has been resolved for you.

**Comment by forsomefun** [comment] 2018-05-10 02:27
You can close it, but I have a question below.  2nd paragraph. 
Yeah the program ended up downloading every show I needed. One thing is that I didn't consider the fact that some people might have feeds that would require having favorites because maybe it's a generic TV feed. 

Mine is specific to me and from showrss. Would it be possible to have every show added to favorites from the beginning. I imagine some shows are not showing up now because they are off season, and aren't being added to the feed from showrss. 

The problem with the download folder seem to be the /root/ location changing it to a different directory like recommended works.

**Comment by dchang0** [comment] 2018-05-10 02:46
Cool, thanks. Glad to hear your download folder problem was fixed.

Re: "Would it be possible to have every show added to favorites from the beginning."

I have thought about a similar problem for a while. For me the problem is this: a new season is about to start, there are plenty of positive previews of shows to look out for, the shows are not yet in any feed for me to use the Add To Favorites button, and I want to quickly input them without pasting the show title into separate New Favorite forms over and over.

I considered the pros and cons of various approaches; most of them have serious downsides. My best idea so far is to create a bulk-importer that allows you to cut and paste a plain text list of show titles, and it converts them all into separate Favorites. It would solve your problem if you know what shows you want and can paste them into a text file, one show title per line. I'm not sure this idea is all that great; maybe I'll build it as a command-line utility and test it on myself for a while before deciding to publish it. It would probably be version 1.1.0 before this feature shows up.

I can say adding every show in a Feed is possible if you can see them in the feed list. Just select them all with Ctrl A (Cmd A on Macs) and then click the Add to Favorites (heart) button in the pop-up toolbar. But if you can't see the show in the feed list, this will not work. Still, you can get dozens or hundreds of shows turned into Favorites this way very easily.

**Closed by dchang0** 2018-05-10 02:46 UTC

**Comment by forsomefun** [comment] 2018-05-10 13:30
Yeah, I think your idea of the bulk importer would work. As long as it was clear how the naming would have to work. 

Not sure if this is normal, but I notice that my showrss feed only goes back about a week. When reading it through rss readers. I think it would help in the case of a show like Game of Thrones which is not in my Feed Right now. So there is no easy way to add it. I'll probably know when the season is starting because that show is so popular. But for every show that might not be true unless I'm really lucky and happen to watch a video reminding me or something. 

By the way thanks for making this. It has been one of the more useful programs I have on my Linux box. Definitely helps with not getting bored at work.

**Comment by dchang0** [comment] 2018-05-10 15:31
Cool. I'll move the bulk importer idea up in priority (will make it sooner).

Re: "showrss feed only goes back about a week"

Yep, that's normal. RSS feeds will drop off older entries. Some RSS readers cache the older entries for longer, making it look like the feeds last longer. It's a good thing the feeds are short, though. torrentwatch-xa would get badly bogged down if it had to parse thousands of feed items.

Glad you find torrentwatch-xa useful--thanks!

**Comment by dchang0** [comment] 2018-05-10 15:59
Re: "I think it would help in the case of a show like Game of Thrones which is not in my Feed Right now. So there is no easy way to add it."

You can add Game of Thrones right now this way:

Click on the Favorites button. In the pop-up window, click New Favorite in the left-hand column. Type Game of Thrones into the Name field and into the Filter field. Click Update. Wait for any feed to show a Game of Thrones torrent.
