### ISSUE TITLE
Magnet info not written to watch folder

### ISSUE THREAD

**Issue by JohnDarkhorse** [dchang0/torrentwatch-xa#18] opened 2021-07-02 15:02 UTC
According to the usage.md, if there is no torrent file linked in the source rss feed, magnet info will be written to the watch folder if using one.

I am using a watch folder (which works great for torrent files), but for some reason magnet info isn't being written to it.

&nbsp;

Specifically, I've mirrored a couple of source site's RSS feeds outside of a cloudflare enclosure.

One feed provides links to torrent files & magnet links  (this feed works fine)

The other feed only provides magnet links.

&nbsp;

There is no longer an issue with TWXA refreshing (as both feeds are not behind cloudflare), so - to test - I found a tv show in the "**magnet only**" feed.

I clicked the downward arrow next to it and then clicked "Download"

Nothing was downloaded or written to the watch directory.

&nbsp;

In other directions, is adding qbittorrent functionality as simple as copying & modifying the transmission-related bits?

**Comment by dchang0** [comment] 2021-07-02 15:48
Hmm. Could you check the /var/log/twxalog file and see what it says in 
DEBUG mode?
It should say whether it had trouble writing the .magnet file.

------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 7/2/2021 08:02:21
Subject: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by JohnDarkhorse** [comment] 2021-07-02 15:57
No "magnet" mentioned in /var/log/twxalog under DEBUG

I've repeated the "download" steps as described in the first post and nothing is popping up in the twxalog, and nothing is being written to the watch folder.

**Comment by dchang0** [comment] 2021-07-02 16:13
Thanks. Could you check for any ERR lines in twxalog?

It would help if you pasted the portion of the log where the .magnet 
should have been downloaded.

------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 7/2/2021 08:57:30
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by JohnDarkhorse** [comment] 2021-07-02 16:18
> Thanks. Could you check for any ERR lines in twxalog?

The most recent ERR lines (going back to yesterday) are for the source URL being unreachable, and a couple from when I was configuring the mirror (it was empty for ~20 and two ERRors occurred during that time)

> It would help if you pasted the portion of the log where the .magnet should have been downloaded.

Nothing is being written to the log when I click "Download" as described previously.

**Comment by dchang0** [comment] 2021-07-03 03:42
What's probably happening is that neither a torrent link nor a magnet 
link are being found in the RSS feed entry/item.
Not that there isn't a link, just that neither one is being discovered.
This might be because the link is to a gzipped-torrent, which 
torrentwatch-xa doesn't yet support.

If you can send me a sample of the RSS feed's raw source code where you 
would expect it to work but it doesn't, that will help. You don't have 
to send a sample that you actually want; you can pick any entry/item and 
use that as an example, so long as it breaks in the same way that you 
observed.


------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 7/2/2021 09:18:18
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by JohnDarkhorse** [comment] 2021-07-03 09:43
I just did the described "download" routine on the following show, as an experiment.  Nothing spawned in the twxalog, nor appeared in the watch folder.

```
<item>
<title>Tosh.0.S05.WEBRip.x264-ION10</title>
<description>Tosh.0.S05.WEBRip.x264-ION10</description>
<link>
magnet:?xt=urn:btih:5558dca347fd5aef28608e32fb4394489504ff90&dn=Tosh.0.S05.WEBRip.x264-ION10&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2940&tr=udp%3A%2F%2F9.rarbg.to%3A2840&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13740&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14780
</link>
<guid>5558dca347fd5aef28608e32fb4394489504ff90</guid>
<pubDate>Sat, 03 Jul 2021 11:15:21 +0200</pubDate>
</item>
```

&nbsp;

> This might be because the link is to a gzipped-torrent

This isn't about downloading torrent files (that works fine, with rss feeds that offer such), but how the magnet info isn't being written to the watch folder.  The RARBG feed only includes magnet links (no links to torrent files)

**Comment by dchang0** [comment] 2021-07-03 15:07
That definitely is a magnet link.
Okay, I'll feed this through my code and see what happens.


------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 7/3/2021 02:43:31
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by dchang0** [comment] 2021-07-05 07:52
Just to confirm:

1) Are you talking about an item that has been Favorited and is not 
being picked up by the cron job, or are you talking about selecting a 
non-Favorited item in the web gui and then clicking the Download (Play) 
button?

2) If the latter, then are you seeing "Waiting for client data..." in 
your web gui, right under the item you tried to download? This is of 
course if you have set Client = Save torrent in folder.

The above bug happens to me, BUT it is not necessarily related to your 
bug. I have not yet set up the test RSS feed using your example item.



------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 7/3/2021 02:43:31
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by JohnDarkhorse** [comment] 2021-07-05 13:25
1) I was clicking on the first RARBG (magnet links only) RSS offering as an experiment - not a "Favorite"

However!  I was just coming here to add some more info about this.

I have favorites that work fine with the magnet+torrent RSS feed, but today - since I've added the magnet-only RSS feed - they failed to download (or even be marked "matching")

As far as I can theorize, the magnet-only feed published the favorites before the magnet-torrent feed and TWXA triggered on the magnet-only favorites, but since no magnet info is being written to the watch directory, nothing was downloaded.

2) Clicking > "Download"ing the random first thing on the magnet-only RSS feed did not trigger any messages anywhere.

&nbsp;

FYI: The magnet+torrent RSS feed's primary URL is https://eztv.re/ezrss.xml

The magnet-only RSS feed's primary URL is https://rarbg.to/rssdd.php?category=2;18;41;49

Both are behind Cloudflare but RARBG has several other (aggressive towards VPN & TOR users) interdiction gateways.

**Comment by dchang0** [comment] 2021-07-05 15:51
Thanks, this is great information!

------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 7/5/2021 06:26:03
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by dchang0** [comment] 2021-07-05 20:19
Okay, I can definitely reproduce the error.

RARBG definitely doesn't work in the web UI when the Download button is 
clicked.

It is generating an HTTP 500 internal server error:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted 
(tried to allocate 20480 bytes) in 
/var/lib/torrentwatch-xa/lib/twxa_tools.php on line 47.

Strangely, line 47 in twxa_tools.php is a pretty innocuous line. This 
will be harder to debug.


------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 7/5/2021 06:26:03
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by dchang0** [comment] 2021-07-05 20:40
Looks like it gets stuck in an infinite loop when trying to start any 
item in RARBG.
Then, when it tries to assign the $curlOptions variable (passed by 
reference into getcURLDefaults()), it runs out of memory no matter how 
much memory you have.

I probably should rewrite the entire getcURLDefaults() function so that 
it doesn't need $curlOptions passed by reference, but there is something 
different about RARBG such that its entries cause an infinite loop.


------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 7/5/2021 06:26:03
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by dchang0** [comment] 2021-07-05 20:55
The loop is being created by insufficient error handling in the function 
client_add_torrent().
When the $filename is empty, it goes into the loop. Nothing was put in 
place to handle this possibility.

This function was carried over from TorrentWatch-X and modified to 
handle .magnet files. I've had a note to rewrite the entire function for 
quite a long while now but have never gotten around to it.

I'll probably rewrite it unless it looks like untangling a can of worms, 
in which case I'll just patch it against the possibility of $filename 
being empty.


------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "Comment" 
***@***.***>
Sent: 7/5/2021 06:26:03
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by dchang0** [comment] 2021-07-05 22:28
This bug is clearly a failure to parse the items in the RSS feed produced by RARBG.

I am not yet sure whether it is because RARBG is not sticking with the RSS standard or if PicoFeed needs to be modified/improved to be able to handle it.

**Comment by JohnDarkhorse** [comment] 2021-07-05 23:24
> RARBG definitely doesn't work in the web UI when the Download button is clicked.

To rule out rarbg being difficult, may I suggest you create a mirror of the rarbg RSS xml file on localhost?  As noted, rarbg has some extreme anti-leeching / anti-bot stuff going on . . .

**Comment by dchang0** [comment] 2021-07-05 23:26
That's a good idea, thanks.

**Comment by dchang0** [comment] 2021-07-06 04:58
I have pinpointed the exact logic that causes the RARBG item url to be blank, and it is the resolve member function of the Url class in PicoFeed

In short, it checks to see whether the URL is absolute or relative, but the real problem is that the URL cannot begin with magnet:.

I found that RARBG's feed fails the official RSS validator provided by the RSS Advisory Board here:

https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Frarbg.to%2Frssdd.php%3Fcategory%3D2%3B18%3B41%3B49

The key rejection is:

"In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 13, column 384: __URI scheme not IANA registered: magnet__ (25 occurrences) [help]

... %3A%2F%2Ftracker.slowcheetah.org%3A14770</link>"

Thus, the proper response here is for torrentwatch-xa to reject RARBG's feed as non-conforming to the RSS 2.0 specification.
I will fix the infinite loop and try to make torrentwatch-xa display a useful error message indicating that the RARBG feed does not conform.

Sadly, this means that you will not be able to use RARBG without rewriting their feed such that it conforms.

**Comment by dchang0** [comment] 2021-07-06 05:26
Oh, if you want to hack PicoFeed so that it allows magnet links in the <link> element, you can disable the URL check by commenting out this line:

/var/lib/torrentwatch-xa/lib/PicoFeed/Parser/Parser.php
line 156:

`$this->checkItemUrl($feed,$item);`

However, this is not enough to fix the HTTP 500 Internal Server Error, so I need to keep working on that.

**Comment by dchang0** [comment] 2021-07-06 06:06
Okay, I have added some logic to client_add_torrent() in twxa_torrent.php to protect against blank links.
This successfully stops the infinite loop and produces a useful error in the web UI and in twxalog.

The bug fix in twxa_torrent.php has been committed and pushed to Github.

I could close this issue now, but I will continue to try to achieve two goals:

1) figure out a hack that allows RARBG to work

2) finally get around to rewriting client_add_torrent(), but this is a daunting task

**Comment by dchang0** [comment] 2021-07-06 06:34
Re: 1. figure out a hack that allows RARBG to work

It doesn't look like this is going to happen because it involves rewriting the function choose_torrent_link() and possibly get_torrent_link() into functions that handle both magnet and torrent links. This would be a lot of effort to make a non-conforming RSS feed work. I'm closing this ticket now, though it is likely that the ability of torrentwatch-xa to handle magnet links still needs to be improved.

**Closed by dchang0** 2021-07-06 06:34 UTC

**Comment by JohnDarkhorse** [comment] 2021-07-06 11:54
Can you provide an example of the magnet link info file that is written out to the watch folder?

**Comment by dchang0** [comment] 2021-07-06 13:28
I don't get what you mean. No magnet link is written out to a file 
because the magnet link is erased by PicoFeed because it does not 
conform to the RSS 2.0 specification.

In order for the magnet link to make it through PicoFeed to where 
torrentwatch-xa can see the magnet link, it would have to be 
properly-enclosed in an <enclosure> tag.

------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "State change" 
***@***.***>
Sent: 7/6/2021 04:54:31
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by JohnDarkhorse** [comment] 2021-07-06 16:47
I'm not trying to get RARBG to work 

I have yet to see a magnet written to a file (as mentioned in the TWXA documentation), and wanted to know what it looked like so as to write a local function to transform the file.magnet to a file.torrent.

&nbsp;

Thanks for the example :)

**Comment by dchang0** [comment] 2021-07-06 16:59
Ohhhhh, okay. I understand now.

In that case, yes, the raw magnet link is written to the plain text 
file. Nothing else (no enclosure, no surrounding HTML or XML tags).

I will add it to my long-term TODO list to bring .magnet links up to 
equal footing with .torrent links. Right now, magnets are written only 
if the torrent link is not found and a magnet is found (both torrent and 
magnet links must be properly-enclosed and RSS-compliant for this to 
occur).


------ Original Message ------
From: "JohnDarkhorse" ***@***.***>
To: "dchang0/torrentwatch-xa" ***@***.***>
Cc: "dchang0" ***@***.***>; "State change" 
***@***.***>
Sent: 7/6/2021 09:47:35
Subject: Re: [dchang0/torrentwatch-xa] Magnet info not written to watch 
folder (#18)

**Comment by JohnDarkhorse** [comment] 2021-07-06 23:42
With the thought that functionality could be added to TWXA, I looked for PHP implementations of "magnet to torrent" functionality here on Github, but all of them I found are nothing more than retrieval methods for itorrents, torcache or similar torrent file repositories.  These are all suboptimal as they depend on the torrent file being uploaded to the repository in the first place.

&nbsp;

There are several python implementations of "magnet to torrent" where the app actually generates a torrent file from a magnet link via libtorrent, but I could not get any to work on my Ubuntu system :( 

Pulling python functionality into a PHP wagon isn't optimal, either

&nbsp;

The only reliable method I've found is via the use of [aria2](https://aria2.github.io/), which takes the magnet link & queries the DHT network for a valid torrent file, which it then downloads.  It works a treat on new content (lots of nodes on the DHT network), but is a command line program.

**Comment by dchang0** [comment] 2021-07-06 23:51
The way aria2 does it is the same way that the various magnet-to-torrent websites I use do it.
It claims that it can be manipulated via JSON-RPC.
But, it is probably possible to do the same thing with transmission-daemon (feed it a magnet link and ask it to export a .torrent file via JSON-RPC).

If I were trying to do what you're doing, I'd use the existing websites and use curl to submit the magnet: link and retrieve the .torrent file. This offloads the bulk of the bandwidth onto the magnet-to-torrent website.

**Comment by dchang0** [comment] 2021-07-07 00:54
BTW, some items in TokyoTosho.info's feed fail to conform to RSS 2.0 specs and are stripped of their magnet or torrent links. I will have to examine the RSS carefully.

**Comment by JohnDarkhorse** [comment] 2021-07-07 01:32
I was merely bouncing ideas here, in an effort to remove the "write magnet file to watch folder" issue entirely from TWXA (instead, TWXA could convert any magnet links to actual torrent files)

>aria2 claims that it can be manipulated via JSON-RPC.

Something like this? ```https://github.com/weirdcrap/magnet2torrent```

> But, it is probably possible to do the same thing with transmission-daemon (feed it a magnet link and ask it to export a .torrent file via JSON-RPC).

Which brings us back to the source of many of my issues - I'm not using Transmission

&nbsp;

Speaking of, would setting this up to use Qbittorrent just be a case of modifying the transmission-related code?

**Comment by dchang0** [comment] 2021-07-07 01:38
https://github.com/weirdcrap/magnet2torrent is just a wrapper for the command line version of aria2c. It doesn't use JSON-RPC.
Not that that's a bad thing. Really, it doesn't matter which way you call aria2, so long as it works reliably.

Re: Qbittorrent

Yes, it should be possible to modify the transmission-related code to work with other bittorrent clients, so long as they can be controlled by RPC. I do not think this will be easy, though. The modifications may require changing dozens of lines of code.

**Comment by dchang0** [comment] 2021-07-07 01:49
Amazingly, TokyoTosho.info validates perfectly.
So, I need to figure out why some of the entries are not working and solve that problem. It's not the same issue as with RARBG.

**Comment by dchang0** [comment] 2021-07-07 03:17
I looked into Qbittorrent. It doesn't seem to have an RPC API. However, it does have a WebUI API, and there happens to be this project that can translate Transmission's RPC into Qbittorrent's WebUI.

https://github.com/h31/Reflection

I have not tried it.

**Comment by dchang0** [comment] 2021-07-07 08:12
The next minor version (probably 1.7.0) will have improved detection of magnet links. I have started rewriting the functions that search through the feed items for any torrent file or magnet links.
It may take a while to release the next version, though, because the rewrite will be substantial.

**Comment by dchang0** [comment] 2021-07-07 16:27
TokyoTosho issue is fixed. It has nothing to do with the feed and everything to do with Nyaa using /torrent at the end of their torrent file links instead of .torrent. Adding /torrent to the function get_torrent_link() solved it easily.

I have started rewriting get_torrent_link() so that it detects magnet: links. There will be a ranking of best links to worst links. The function choose_torrent_link() goes down the ranking and picks just one link. I'll write two new functions--one to pick the best magnet link and one to pick the best torrent file link. I might add a configuration option where the user can set whether they prefer .torrent files or magnet: links or both. Not sure what to do about that.

**Comment by dchang0** [comment] 2021-07-08 19:38
I think the reason that you have not seen any magnet: links get written to any files is that PicoFeed removes all magnet: links when it sees them.
I will have to hack PicoFeed to allow them, which will incidentally make RARBG work.

**Comment by dchang0** [comment] 2021-07-11 22:43
I am modifying PicoFeed to allow magnet: links right now. That's not the only thing that has to be modified to allow magnet: links, of course.

**Comment by dchang0** [comment] 2021-07-12 02:11
RARBG now works (to be released in 1.7.0). This ticket is truly closed now.

**Comment by dchang0** [comment] 2021-07-14 20:01
I can confirm that 1.7.0 writes magnet files to folders. I used a Favorite in the RARBG feed to test this, and the functionality is back.
Unfortunately, it will be a while before 1.7.0 is released because there are other, big bugs to fix (mainly related to Save Torrent In Folder).

**Comment by dchang0** [comment] 2021-07-14 20:36
Could I ask you to test these new files? I decided to commit and push these without testing them in 1.6.0 without waiting for 1.7.0.

In this folder:

var/lib/torrentwatch-xa/lib/Parser

get these new files:

Item.php
Rss20.php
Atom.php
Parser.php

They have been modified to allow magnet: links.
