### ISSUE TITLE
Release update notification showing up, even if there is no relase tag

### ISSUE THREAD

**Issue by efelon** [dchang0/torrentwatch-xa#5] opened 2018-07-02 11:23 UTC
Hi,

this is a very small issue for 1.0.0 from the release tags.

Beside the title, I think you don't need more information. Other than maybe the message only pops up once stating that 1.1.0 is available.

Best regards,
Martin

**Comment by dchang0** [comment] 2018-07-02 16:13
Ah yes. This is not a bug--version 1.1.0 really is available. (There _was_ a bug with the version comparison logic in 0.9.0 and all prior versions, but it was fixed in 1.0.0. You have the fix.) You can get 1.1.0 not from the Releases page yet but by clicking the Clone or Download button on the project's main page. I will release 1.1.0 after I'm sure there are no further minor bugfixes.

I added a feature in 1.1.0 called Check for Updates which, if unchecked, will turn off the check for newer versions.

If you don't want to upgrade from 1.0.0 to 1.1.0 yet, here is how you can stop the version checks permanently:

Find this line in /var/www/html/torrentwatch-xa/torrentwatch-xa.php:

`echo checkVersion($twxa_version);`

And comment it out by putting two forward slashes in front of it like so:

`//echo checkVersion($twxa_version);`

That will cut off the check for updates.

But I strongly encourage you to upgrade to 1.1.0 if possible, because:

1) 1.1.0 fixes a very bad bug with the config file getting half-erased with default settings in very rare circumstances.

2) 1.1.0 has a command-line bulk Favorites importer tool (in alpha testing), which is perfect now that a new season of anime is just about to start. You can read various anime previews, type their info into a simple Tab-Separated Values (TSV) file, then import them into Favorites.

**Closed by dchang0** 2018-07-02 16:13 UTC

**Comment by dchang0** [comment] 2018-07-02 16:18
I forgot to explain: I follow a delayed release schedule. The newest version is pushed to the repo and the version number is updated, but it is not actually released to the Releases tags until a few weeks or months have passed, in case people find small bugs.

Come to think of it, no one has reported any bugs with 1.1.0, so I will release it now. Thanks!
